Support node 16 and 18
checkdigit/asyncerator pull request #39
Opened 2022-08-31 19:01 UTC by carlansley

2022-08-31 19:59 UTC, carlansley commented on .github/workflows/ci.yml
> +        run: npm audit signatures
@adcreare note that we can use ^ this now with the latest version of node 16.  I think we should do this when building for deployment also.

2022-08-31 21:51 UTC, ramaghanta requested changes
couple of minor changes

2022-08-31 21:51 UTC, ramaghanta commented on src/node/socket.spec.ts
> +import assert from 'node:assert';
`{ strict as assert }`

2022-08-31 21:51 UTC, ramaghanta commented on src/node/stream-consumers.spec.ts
> +import assert from 'node:assert';
`{ strict as assert }`

2022-08-31 21:51 UTC, ramaghanta commented on src/node/stream-consumers.spec.ts
> +import * as stream from 'node:stream';
`import stream from 'node:stream'`

2022-09-01 09:55 UTC, adcreare approved these changes
LGTM

2022-09-01 19:47 UTC, ramaghanta approved these changes
lgtm

2022-09-01 19:47 UTC, merged